### PR TITLE
added option to disable normalization of cluster names

### PR DESCRIPTION
**Pull request by mupplelabs**

### CODE REVIEW

**Review by tenortim — CHANGES_REQUESTED** [review]
I think we need to be able to do this, but I would like the default to remain "true". That won't work with the code as it is because if the entry is missing, it's going to default to the default zero value for the type which is false. So either the struct entry needs to be made into a pointer (so we can distinguish between no value: nil vs false), or the name of the parameter could be changed to something like "preserve_case" because that way, the default of false would give us unchanged behavior.

Do you want to make these changes or should I do it?

**Comment by mupplelabs** [comment]
Agreed, let me have a look into it.

**Comment by mupplelabs** [comment]
While looking into it. Wouldnt it be good to have this option per Cluster instead of it being a global setting?

**Comment by tenortim** [comment]
I had originally thought about making it global because I couldn't come up with a scenario where you'd want it to be per-cluster, but I have no objections to making it so :)

**Comment by tenortim** [comment]
After discussing this with Stefan, he is going to rework the change and submit a new PR, so closing this original PR without merging.

**Pull request closed without merging**
